language: ruby
rvm:
  - 2.2
  - jruby
addons:
    code_climate:
        repo_token: c0bf48b552db5bcc7798295383246fb9af7918a77094d6ca0af225fc8d4210cd
after_success:
  - bundle exec codeclimate-test-reporter
